### ISSUE TITLE
Client autotools_ls quit with exit code 1 and signal 0

### ISSUE THREAD

**Issue by Mblakey** [Freed-Wu/autotools-language-server#12]
Probably the same as the other closed issues, although different error messages in the logs on my end. 

Ubuntu 24.04 LTS, installed through Mason. Nvim release version 0.10.1

[ERROR][2024-10-10 14:09:15] .../vim/lsp/rpc.lua:770	"rpc"	"autotools-language-server"	"stderr"	'    MakeLanguageServer(NAME, __version__).start_io()\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/mikey/.local/share/nvim/mason/packages/autotools-language-server/venv/lib/python3.12/site-packages/make_language_server/server.py", line 55, in __init__\n    self.parser = get_parser("make")\n                  ^^^^^^^^^^^^^^^^^^\n  File "tree_sitter_languages/core.pyx", line 19, in tree_sitter_languages.core.get_parser\n  File "tree_sitter_languages/core.pyx", line 14, in tree_sitter_languages.core.get_language\nTypeError: __init__() takes exactly 1 argument (2 given)\n'

**Comment by Freed-Wu** [comment]
I think #8 and #11 should be the reason. Update to 0.0.19 should fix the problem.

**Comment by Freed-Wu** [comment]
It should be finished manually, I think.

**Comment by wangxa** [comment]
The methods you mentioned in #8 and #11 are not working. Because:

Mason installs the language servers in its own directory, i.e., `~/.local/share/nvim/mason/packages/autotools-language-server/venv/`; while, pip install them in `./local`. So, even we installed 0.0.19, nvim `Make language server` is still running the one installed by mason, version 0.0.18.

**Comment by Mblakey** [comment]
@wangxa you can move the files into Mason and do a custom install. But I agree, I won't be using this repo until Mason can install the current version properly.

**Comment by wangxa** [comment]
OK. Thnak you.

**Comment by Freed-Wu** [comment]
`pip install --prefix /the/path/you/want` should work.

**Comment by cxwx** [comment]
same issue

**Comment by Freed-Wu** [comment]
Yes, same as #11
